- hosts: all
  become: True

  tasks:
    - name: install necessary pkgs for Node.js runtime
      apk: name={{ item }} state=latest
      with_items:
        - nodejs

#    - name: install app
#      npm:
#        name: json-server
#        global: yes
#        production: yes
#        state: latest

    - name: install app
      command: npm install -g --production json-server

    - name: remove unused temp
      file: path={{ item }}  state=absent
      with_items:
        - "/root/.npm"
        - "/usr/lib/node_modules/npm"